# Generated by Django 4.2.9 on 2024-03-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="service", name="product",),
        migrations.CreateModel(
            name="ServiceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utilizacao", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="products",
            field=models.ManyToManyField(
                related_name="services",
                through="service.ServiceProduct",
                to="product.product",
            ),
        ),
    ]
