# Generated by Django 4.2.9 on 2024-03-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service", old_name="raw_material", new_name="product",
        ),
    ]
