# Generated by Django 4.2.9 on 2024-03-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professional", "0001_initial"),
        ("product", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_type", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField()),
                (
                    "alternative_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cust_sale",
                        to="customer.customer",
                    ),
                ),
                ("products", models.ManyToManyField(to="product.product")),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profess_sale",
                        to="professional.professional",
                    ),
                ),
            ],
        ),
    ]
