# Generated by Django 4.1.6 on 2024-03-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryimage",
            name="cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productimage",
            name="cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="cover",
            field=models.BooleanField(default=False),
        ),
    ]
